language: python

python:
  - '2.7'
  - '3.4'

sudo: false

install: pip install tox

git:
  depth: 1

branches:
  except:
  - gh-pages

before_script:
  - chmod +x ./run_test.sh

script:
  - ./run_test.sh
