language: python

matrix:
  include:
  - python: "2.7"
    env: TEST_PY=py27

sudo: false

install:
  - pip install tox
  - pip install flake8

git:
  depth: 1

branches:
  except:
  - gh-pages

before_script:
  - chmod +x ./run_test.sh
  - flake8 ./$INFORTREND_DRIVER_DIR/
  - flake8 ./$INFORTREND_TEST_DIR/

script:
  ./run_test.sh $TEST_PY
